### ISSUE TITLE
Wrong ARCADE version from arcadeVersion

### ISSUE THREAD

**Issue by jsdpag** [esi-neuroscience/ARCADE#27]
ARCADE v2.6.0 prints:

`2.5.7-50-gbb95462`

at launch.

Presumably, this is because the system call to:

`git.exe -C <arcaderoot> describe`

returns the wrong version string.

See [arcadeVersion.m](https://github.com/esi-neuroscience/ARCADE/blob/7b9ac7136e87b33fad22fa1b71f5502aee0cb8dd/arcade/Core/arcadeVersion.m) line [number 4](https://github.com/esi-neuroscience/ARCADE/blob/7b9ac7136e87b33fad22fa1b71f5502aee0cb8dd/arcade/Core/arcadeVersion.m#L4).

**Comment by pantaray** [comment]
Hi! Thanks for reporting this - I'll look into it.

**Comment by pantaray** [comment]
Hm, my bad: release 2.6 points to a "lightweight" git tag, which confuses `git describe`. I changed the version fetching mechanism to use `git describe --tags` instead (cf 4020e70 works with both lightweight and annotated tags). Please `git pull` and give it a go.

**Comment by jsdpag** [comment]
Sorry, I’m still getting

`ARCADE version: 2.5.7-52-g8a62823 (git)`

In the preamble.
